CREATE TABLESPACE "APPBIBLIO" LOGGING 
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\APPBIBLIO.dbf' SIZE 24M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


DROP USER biblio CASCADE;

CREATE USER biblio IDENTIFIED BY biblio
       DEFAULT TABLESPACE APPbiblio  
       TEMPORARY TABLESPACE temp
       ACCOUNT UNLOCK;

GRANT "CONNECT" TO biblio;
GRANT "RESOURCE" TO biblio;

GRANT ALTER ANY INDEX TO biblio;
GRANT ALTER ANY SEQUENCE TO biblio;
GRANT ALTER ANY TABLE TO biblio;
GRANT ALTER ANY TRIGGER TO biblio;
GRANT CREATE ANY INDEX TO biblio;
GRANT CREATE ANY SEQUENCE TO biblio;
GRANT CREATE ANY SYNONYM TO biblio;
GRANT CREATE ANY TABLE TO biblio;
GRANT CREATE ANY TRIGGER TO biblio;
GRANT CREATE ANY VIEW TO biblio;
GRANT CREATE PROCEDURE TO biblio;
GRANT CREATE PUBLIC SYNONYM TO biblio;
GRANT CREATE TRIGGER TO biblio;
GRANT CREATE VIEW TO biblio;
GRANT DELETE ANY TABLE TO biblio;
GRANT DROP ANY INDEX TO biblio;
GRANT DROP ANY SEQUENCE TO biblio;
GRANT DROP ANY TABLE TO biblio;

